version: 2

jobs:
  server:
    docker:
      - image: node:10-stretch
    steps:
      - checkout

      - restore_cache:
          key: npm-cache-server-{{ checksum "server/package.json" }}

      - run:
          name: Install node packages
          command: cd server && npm install

      - run:
          name: Run TS Lint
          command: cd server && npm run ts:lint

      - run:
          name: Run TSC
          command: cd server && npm run ts:compile

      - save_cache:
          paths:
            - server/node_modules
          key: npm-cache-server-{{ checksum "server/package.json" }}

  client:
    docker:
      - image: node:10-stretch
    steps:
      - checkout

      - restore_cache:
          key: npm-cache-client-{{ checksum "client/package.json" }}

      - run:
          name: Install node packages
          command: cd client && npm install

      - run:
          name: Build Angular app
          command: cd client && node_modules/.bin/ng build --prod

      - save_cache:
          paths:
            - client/node_modules
          key: npm-cache-client-{{ checksum "client/package.json" }}

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST -p$SSH_PORT $SSH_COMMAND

workflows:
  version: 2
  build:
    jobs:
      - server
      - client
      - deploy:
          requires:
            - server
            - client
          filters:
            branches:
              only: master
