version: 2

jobs:
  server:
    docker:
      - image: circleci/node:10-stretch
      #- image: circleci/postgres:10-alpine
    steps:
      - checkout

      - restore_cache:
          key: npm-cache-server-{{ checksum "server/package-lock.json" }}

      - run:
          name: Install Node packages
          command: cd server && npm install

      - save_cache:
          paths:
            - server/node_modules
          key: npm-cache-server-{{ checksum "server/package-lock.json" }}

      - run:
          name: Run TS Lint
          command: cd server && npm run ts:lint

      - run:
          name: Run TSC
          command: cd server && npm run ts:compile

      - run:
          name: Unit Tests
          command: cd server && npm test

  client:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - checkout

      - restore_cache:
          key: npm-cache-client-{{ checksum "client/package-lock.json" }}

      - run:
          name: Install Node packages
          command: cd client && npm install

      - save_cache:
          paths:
            - client/node_modules
          key: npm-cache-client-{{ checksum "client/package-lock.json" }}

      - run:
          name: Run Angular Linting
          command: cd client && npm run lint

      - run:
          name: Angular Spec (Karma/Jasmine) Tests
          command: cd client && npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - run:
          name: Angular Spec (Karma/Jasmine) Tests
          command: cd client && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

      # - run:
      #     name: Build Angular app
      #     command: cd client && node_modules/.bin/ng build --prod

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST -p$SSH_PORT $SSH_COMMAND

workflows:
  version: 2
  build:
    jobs:
      - server
      - client
      - deploy:
          requires:
            - server
            - client
          filters:
            branches:
              only: master
